
import com.mysql.cj.jdbc.PreparedStatement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Thasneem
 */
public class edit_delete_drugs extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form edit_delete_drugs
     */
    main_class main = new main_class();
    public edit_delete_drugs() {
        initComponents();
        showDrugsFromTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        drug_name01 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        drug_formula01 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        drug_mfd01 = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        drug_exp01 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        drugtable = new javax.swing.JTable();
        drug_delete = new javax.swing.JButton();
        drug_update = new javax.swing.JButton();
        ok_btn = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("DRUG NAME");

        jLabel2.setText("DRUG FORMULA");

        jLabel3.setText("DRUG mfd.date");

        jLabel4.setText("DRUG exp.date");

        drugtable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Name", "Formula", "Mfd Date", "Exp Date"
            }
        ));
        drugtable.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                drugtableMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(drugtable);

        drug_delete.setBackground(new java.awt.Color(255, 102, 102));
        drug_delete.setText("DELETE");
        drug_delete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drug_deleteActionPerformed(evt);
            }
        });

        drug_update.setText("UPDATE");
        drug_update.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                drug_updateActionPerformed(evt);
            }
        });

        ok_btn.setText("OK");
        ok_btn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ok_btnActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Times New Roman", 3, 18)); // NOI18N
        jLabel5.setText("EDIT / DELETE DRUGS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 527, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(drug_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(drug_update, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(16, 16, 16))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 92, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45))))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(drug_exp01, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(drug_mfd01, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(drug_formula01, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 138, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(59, 59, 59)
                                .addComponent(drug_name01, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(272, 272, 272)
                        .addComponent(jLabel5)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(jLabel5)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(drug_name01, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(drug_formula01, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(drug_mfd01, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(drug_exp01, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 373, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(7, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(drug_update, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(73, 73, 73)
                        .addComponent(drug_delete, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(68, 68, 68)
                        .addComponent(ok_btn, javax.swing.GroupLayout.PREFERRED_SIZE, 35, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(63, 63, 63))))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    
        public ArrayList<drugs_data> getDrugsList(){
    ArrayList<drugs_data> drugsList = new ArrayList<drugs_data>();
    Connection Conn = main.getConnection();
    String sql = "Select * from drugs";
    Statement stmt;
    ResultSet rs;
    
    try{
        stmt = Conn.createStatement();
        rs = stmt.executeQuery(sql);
        drugs_data drugs;
        
        while (rs.next()){
            drugs = new drugs_data(rs.getString("drug_name"),rs.getString("drug_formula"),rs.getString("drug_mfd"),rs.getString("drug_exp"));
            drugsList.add(drugs);
        }
    } catch(SQLException e){
        Logger.getLogger(edit_delete_drugs.class.getName()).log(Level.SEVERE,null,e);
    }return drugsList;
}
public void showDrugsFromTable(){
    ArrayList<drugs_data> list = getDrugsList();
    DefaultTableModel model = (DefaultTableModel) drugtable.getModel();
    model.setRowCount(0);
    Object[]row = new Object[4];
    for (int x=0; x< list.size();x++){
        row[0] = list.get(x).getdname();
        row[1] = list.get(x).getdformula();
        row[2] = list.get(x).getdmfd();
        row[3] = list.get(x).getdexp();
        model.addRow(row);
        
    }
    
}

    private void drugtableMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_drugtableMouseClicked
        // TODO add your handling code here:
        int index = drugtable.getSelectedRow();
        showItem(index);
    }//GEN-LAST:event_drugtableMouseClicked
    
     public void showItem(int index) {
        drug_name01.setText (getDrugsList ().get (index).getdname());
        drug_formula01.setText(getDrugsList().get(index).getdformula());
        drug_mfd01.setText(getDrugsList().get(index).getdmfd());
        drug_exp01.setText(getDrugsList().get (index).getdexp ());
   }
    private void drug_updateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drug_updateActionPerformed
        // TODO add your handling code here:
        try{
            String UpdateQuery=null;
            PreparedStatement ps = null;
            Connection Conn = main.getConnection();
            
            UpdateQuery = "UPDATE drugs SET drug_name = ? ,drug_formula = ?, drug_mfd = ? , drug_exp = ?";
            ps = (PreparedStatement) Conn.prepareCall(UpdateQuery);
            
            ps.setString (1, drug_name01.getText());
            ps.setString (2,drug_formula01.getText());
            ps.setString(3, drug_mfd01.getText());
            ps.setString (4, drug_exp01.getText());
            ps.executeUpdate();
            
            JOptionPane.showMessageDialog (null, "Employee Details Updated!");
            showDrugsFromTable();
        }catch (SQLException e) {
            Logger.getLogger (edit_delete_drugs.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_drug_updateActionPerformed

    private void drug_deleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_drug_deleteActionPerformed
        // TODO add your handling code here:
        String DrugName = drug_name01.getText();
        try {
            if(DrugName.equals("")){
                JOptionPane.showMessageDialog(null, "No DRUG is Selected");
            } else {
                Connection conn = main.getConnection();
                Statement stmt = conn.createStatement();
                
                String sql ="DELETE FROM `drugs` WHERE `drug_name` ='"+DrugName+"'";
                stmt.executeUpdate(sql);
                String msg = "Drug was deleted frome pharmacy";
                JOptionPane. showMessageDialog (null, msg);
                showDrugsFromTable();

            }
        }catch (SQLException e) {
            String retry = "Plesse Try Again(!)";
            JOptionPane.showMessageDialog(null, retry);
        }
    }//GEN-LAST:event_drug_deleteActionPerformed

    private void ok_btnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ok_btnActionPerformed
        // TODO add your handling code here:
        new pick_fram().setVisible(true);
       this.dispose();
    }//GEN-LAST:event_ok_btnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(edit_delete_drugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(edit_delete_drugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(edit_delete_drugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(edit_delete_drugs.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new edit_delete_drugs().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton drug_delete;
    private javax.swing.JTextField drug_exp01;
    private javax.swing.JTextField drug_formula01;
    private javax.swing.JTextField drug_mfd01;
    private javax.swing.JTextField drug_name01;
    private javax.swing.JButton drug_update;
    private javax.swing.JTable drugtable;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JButton ok_btn;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
